package ru.igromania.server.utils;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Locale;

public class Constraints {

    //Templates for parsing
    public static final String templateForDiv = "div[class=%s]";
    public static final String templateForHardDiv = "div[class=%s][itemprop=articleBody][data-io-article-url=%s]";
    public static final String templateForSpan = "span[class=%s]";
    public static final String templateForImage = "img[class=%s]";
    public static final String templateForP = "p[class=%s]";
    public static final String templateForA = "a[class=%s]";
    public static final String templateForH1 = "h1[class=%s]";
    public static final String templateForGamesLink = "https://www.igromania.ru/games/all/all/all/all/all/0/%d/release_asc/";
    public static final String templateForGame = "https://www.igromania.ru/game/%d/";


    //Format for parsing string date like 16.11.2020
    public static final DateFormat format = new SimpleDateFormat("dd.MM.yyyy", Locale.ENGLISH);

    // Array of game genres
    private static String[] genresArray = {"Beat-em-Up",
            "FPS",
            "Hack And Slash",
            "MMO",
            "MOBA",
            "Point & Click",
            "Roguelike",
            "TD",
            "TPS",
            "Аркада",
            "Визуальная новелла",
            "Выживание",
            "Гонки",
            "Игра для взрослых",
            "Интерактивное кино",
            "История",
            "Квест",
            "ККИ",
            "Кооператив",
            "Менеджер",
            "Метроидвания",
            "Музыка",
            "Настольная игра",
            "Обучение",
            "Паззл",
            "Платформер",
            "Пошаговая стратегия",
            "Приключение",
            "Ролевая игра",
            "Симулятор",
            "Симулятор ходьбы",
            "Спорт",
            "Стелс",
            "Стратегия",
            "Стратегия в реальном времени",
            "Тактика",
            "Файтинг",
            "Хоррор",
            "Шутер",
            "Экшен"};

    // List of genres, made to use .contains method
    public static final List<String> genres = new ArrayList<>(Arrays.asList(genresArray));


    public static String[] platformsArray = {
            "PC",
            "Xbox One",
            "PlayStation 5",
            "PS4",
            "Xbox Series",
            "Nintendo Switch",
            "PS3",
            "Wii",
            "Xbox 360",
            "Wii U",
            "PS Vita",
            "NDS",
            "3DS",
            "Android",
            "iOS",
            "2DS",
            "3DO",
            "Acorn Archimedes",
            "Acorn Electron",
            "Amiga",
            "Amstrad CPC",
            "Apple II",
            "Apple Pippin",
            "Arcade automats",
            "Atari",
            "Atari 2600",
            "Atari 5200",
            "Atari 7800",
            "Atari 8-bit",
            "Atari Flashback",
            "Atari Lynx",
            "Atari ST",
            "Atari XEGS",
            "BBC Micro",
            "BlackBerry",
            "Capcom Home Arcade",
            "CD-i",
            "Classic Macintosh",
            "ColecoVision",
            "Commodore 64",
            "CP System",
            "Dingoo A320",
            "Dragon",
            "Enterprise",
            "Epoch Cassette Vision",
            "Facebook",
            "FM Towns",
            "FreeBSD",
            "Fujitsu Micro",
            "Game & Watch",
            "Game Gear",
            "Game.com",
            "GameCube",
            "GB",
            "GBA",
            "GBC",
            "Google Stadia",
            "GP2X Wiz",
            "HTC Vive",
            "IBM PC",
            "Intellivision",
            "Intellivision Amico",
            "iQue Player",
            "Jaguar",
            "Linux",
            "Mac",
            "Mobile Phones",
            "MS-DOS",
            "MSX",
            "MTX",
            "N-Gage",
            "N64",
            "NEC PC",
            "Neo Geo Pocket Color",
            "Neo-Geo",
            "NES",
            "New 3DS",
            "Nintendo Classic Mini: SNES",
            "Nintendo DSi",
            "NVIDIA Shield",
            "NX",
            "Pocket PC",
            "PS",
            "PS2",
            "PS4 Pro",
            "PSP",
            "SAM Coupe",
            "Satellaview",
            "SEGA 32X",
            "Sega CD",
            "Sega Dreamcast",
            "Sega Genesis",
            "Sega Master System",
            "Sega Mega-Tech",
            "Sega Pico",
            "Sega Saturn",
            "SG-1000",
            "Sharp X1",
            "Sharp X68000",
            "SNES",
            "Steam Machines",
            "SuperGrafx",
            "Tandy 1000",
            "Thomson",
            "TI-99/4A",
            "Timex Sinclair",
            "TRS-80",
            "TurboGrafx-16",
            "Unix",
            "Vectrex",
            "Virtual Boy",
            "VR",
            "Web",
            "Windows Mobile",
            "WonderSwan",
            "Xbox",
            "Xbox One X",
            "Zeebo",
            "ZX Spectrum",
            "Консоли",
            "Социальные сети",
            "Электрочайники",
            "Все платформы"
    };

    public static final List<String> platforms = new ArrayList<>(Arrays.asList(platformsArray));
}